#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#undef MASTER_RIGHT
#define MASTER_LEFT

#undef MASTER_LEFT
#define MASTER_RIGHT

// #define SPLIT_POINTING_ENABLE
// #define POINTING_DEVICE_RIGHT

#define ENABLE_RGB_MATRIX_CYCLE_ALL
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT
#define ENABLE_RGB_MATRIX_TYPING_HEATMAP
#define ENABLE_RGB_MATRIX_DIGITAL_RAIN
#define ENABLE_RGB_MATRIX_SPLASH
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_PIXEL_RAIN

#define PMW33XX_CPI 900
